### ISSUE TITLE
FontFamily "AvenirNext-Medium" is not a system font

### ISSUE THREAD

**Issue by grilosape** [sekizlipenguen/react-native-scrolling-menu#11]
Hi,
Very good job in your component for the horizontal scrolling menu.
However, I have had this issue only for Android. Any suggestions?
_fontFamily "AvenirNext-Medium" is not a system font and has not been loaded through Font.loadAsync._

**Comment by sekizlipenguen** [comment]
thank you. You can define your own properties using the textStyle property.

```
<ScrollingButtonMenu textStyle={{
        color: '#5d5d5d',
        fontFamily: 'customFontFamily',
        fontSize: 14,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        lineHeight: 20,
    }}/>
```
