### ISSUE TITLE
index 0 condition 

### ISSUE THREAD

**Issue by KM8Oz** [sekizlipenguen/react-native-scrolling-menu#12]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-scroll-menu@1.0.7` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-scroll-menu/lib/index.js b/node_modules/react-native-scroll-menu/lib/index.js
index f65de3b..fdaa32e 100644
--- a/node_modules/react-native-scroll-menu/lib/index.js
+++ b/node_modules/react-native-scroll-menu/lib/index.js
@@ -87,10 +87,14 @@ export default class ScrollingButtonMenu extends React.Component {
                         items.map((route, i) => (
                             <TouchableOpacity
                                 style={[
+                                    {
+                                        marginLeft:i == 0 ? 12 : 0,
+                                        marginRight:i == items.length-1 ? 12 : 0,
+                                    },
                                     styles.tabItem,
                                     (index === route.id ? styles.tabItemFocused : {}),
                                     (buttonStyle ? buttonStyle : false),
-                                    (index === route.id && activeBackgroundColor ? {backgroundColor: activeBackgroundColor} : false),
+                                    (index === route.id && activeBackgroundColor ? {backgroundColor: activeBackgroundColor} : index == route.id ? {backgroundColor:"#13202F"} : false),
                                 ]}
                                 key={(route.id ? route.id : i).toString()}
                                 onPress={() => this.setState({index: route.id}, () => setTimeout(() => {
@@ -156,7 +160,7 @@ ScrollingButtonMenu.defaultProps = {
 
 const styles = StyleSheet.create({
     scrollArea: {
-        paddingLeft: 20,
+        paddingLeft: 0,
         paddingTop: 20,
     },
     scroll: {},
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sekizlipenguen** [comment]
Hi,

Have you tried using this feature?
` (index === route.id && activeBackgroundColor ? {backgroundColor: activeBackgroundColor} : index == route.id ? {backgroundColor:"#13202F"} : false)`

activeBackgroundColor={'#13202F'} and containerStyle={{paddingLeft: 0}}

I added two more features(props)
firstButtonStyle={{marginLeft:0}}
lastButtonStyle={{marginRight:12}}


activeTextStyle,
activeButtonStyle,
firstButtonStyle,
lastButtonStyle,
containerStyle,
contentContainerStyle,
scrollStyle


would these be enough for you? :)

https://github.com/sekizlipenguen/react-native-scrolling-menu/commit/5e6468dcb57487bf38f3d17c2c8eac7e3c1ad649

**Comment by KM8Oz** [comment]
you can close this at anytime since it's not really an issue and I generated it with patch-package tool.
