### ISSUE TITLE
Keep Selected Opacity

### ISSUE THREAD

**Issue by giuseppepastore10** [sekizlipenguen/react-native-scrolling-menu#2]
Hi,

I'm using your component for horizontal scrolling menu and your work is very good!
However, I'm having some problems as I'd like that the opacity I define for the prop "selectedOpacity" is kept until the selection change and not only when the button is pressed. Can you help me to obtain this behaviour?

**Comment by sekizlipenguen** [comment]
Hi,

Thanks for your opinion,

The issue that you had, has been solved the updated that I release last night. If you still have that problem could you update component?

Let me know, if problem solved, then I close the issue

**Comment by sekizlipenguen** [comment]
The paramaters which are “selected” and “id” should be integer.
